# https://github.com/D3Ext/aesthetic-wallpapers/blob/main/pages/Page1.md
# https://github.com/dharmx/walls
# https://wallhaven.cc/
# https://www.wallpaperflare.com/
#
$wallpaper = ~/.config/hypr/wallpaper2.png
preload = $wallpaper
wallpaper = ,$wallpaper
