# https://wiki.hyprland.org/Configuring/

### ASUS DEFAULTS ### supergfxctl asusctl
exec-once = asusctl --chg-limit 60
exec-once = asusctl slash -d
exec-once = asusctl aura static -c 6B08FF
## exec-once = rog-control-center

### AUTO START ###
exec-once = hyprpaper
exec-once = waybar
# exec-once = hyprpanel

# clipboard
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

### CONFIG ###
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/keymaps.conf
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/appearance.conf
source = ~/.config/hypr/config/rules.conf

### OPTIONS ###
misc {
  font_family = "JetBrainsMono Nerd Font"
  disable_hyprland_logo = true
  focus_on_activate = true
}


