### INPUT ###

input {
  kb_layout = us
  kb_options = caps:super
  follow_mouse = 2
  sensitivity = 0
  accel_profile = "flat"

  touchpad {
    natural_scroll = true
    scroll_factor = .4
    disable_while_typing = true
  }
}
# WORKING FN KEYS
# F1 mute
# F6 screenshot (done by me)
# F7 screen brightness (doesnt interact with hyprpanel)
# F8 screen brightness (doesnt interact with hyprpanel)
# F9 switches between workscaces
# F11 sleeps

### KEYBINDINGS ###
bind = SUPER SHIFT, ESCAPE, exit,
bind = SUPER, BACKSPACE, killactive,
bind = SUPER SHIFT, BACKSPACE, forcekillactive,

# APPs
bind = SUPER, SPACE, exec, $menu
bind = SUPER, BACKSLASH, exec, $fileManager
bind = SUPER, B, exec, $browser
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, D, exec, vesktop
bind = SUPER, S, exec, prime-run steam

# Tools
bind = SUPER SHIFT, P, exec, hyprpicker -a
bind = SUPER SHIFT, S, exec, grim -g "$(slurp -d)" - | wl-copy
bind = SUPER CONTROL SHIFT, S, exec, grim - | wl-copy
bind = SUPER SHIFT, V, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy

# Window Modifications
bind = SUPER, F, fullscreen
bind = SUPER SHIFT, F, togglefloating
bind = SUPER SHIFT, M, layoutmsg, focusmaster
bind = SUPER SHIFT, M, layoutmsg, swapwithmaster

# Window Re-Focus
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d
# Window Re-Positioning
bind = SUPER SHIFT, J, movewindow, d
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
# Window Re-Sizing
binde = SUPER, DOWN,  resizeactive,   0  20
binde = SUPER, UP,    resizeactive,   0 -20
binde = SUPER, LEFT,  resizeactive, -20   0
binde = SUPER, RIGHT, resizeactive,  20   0
# Window Re-Position to Workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Workspace Switching [0-9]
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10
# Workspace Scrolling
binde = SUPER, N, workspace, e+1
binde = SUPER, P, workspace, e-1

# M1 M2 M3
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
# fn F1 F2 F3
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86MonBrightnessDown, exec, brightnessctl -d nvidia_0 s 10%- && brightnessctl -d amdgpu_bl1 s 10%-
bind = , XF86MonBrightnessUp, exec, brightnessctl -d nvidia_0 s 10%+ && brightnessctl -d amdgpu_bl1 s 10%+

# fn F7 F8
bindel = ,XF86KbdBrightnessDown, exec, brightnessctl -d asus::kbd_backlight s 1-
bindel = ,XF86KbdBrightnessUp, exec, brightnessctl -d asus::kbd_backlight s +1

# Config
bind = SUPER ALT, H , exec, kitty nvim ~/.config/hypr/hyprland.conf
bind = SUPER ALT, K , exec, kitty nvim ~/.config/kitty/kitty.conf
bind = SUPER ALT, F , exec, kitty nvim ~/.config/fish/config.fish
bind = SUPER ALT, P , exec, kitty nvim ~/.config/hyprpanel/config.json
bind = SUPER ALT, R , exec, kitty nvim ~/.config/rog/rog-user.cfg
