### WINDOW RULES ###

# pavucontrol
windowrule = float,class:(.*org.pulseaudio.pavucontrol.*)
windowrule = size 700 600,class:(.*org.pulseaudio.pavucontrol.*)
windowrule = center,class:(.*org.pulseaudio.pavucontrol.*)
windowrule = pin,class:(.*org.pulseaudio.pavucontrol.*)

# nm-connection-editor
windowrule = float,class:(nm-connection-editor)
windowrule = size 700 600,class:(nm-connection-editor)
windowrule = center,class:(nm-connection-editor)
windowrule = pin,class:(nm-connection-editor)

# Blueman Manager
windowrule = float,class:(blueman-manager)
windowrule = size 800 600,class:(blueman-manager)
windowrule = center,class:(blueman-manager)
windowrule = pin,class:(blueman-manager)

# rog control center
windowrule = float,class:(rog-control-center)
windowrule = size 800 600,class:(rog-control-center)
windowrule = center,class:(rog-control-center)
windowrule = pin,class:(rog-control-center)
